const mentors=[
{name:'Alexis Jordan',title:'Career Coach',category:'Career',price:75,img:'https://i.pravatar.cc/500?img=47',tags:['Career','LinkedIn','Job Search'],bio:'I help professionals gain clarity, build confidence, and create career paths they love.',offers:[['1:1 Career Coaching',45,75]]},
{name:'Marcus Williams',title:'Business Strategist',category:'Business',price:100,img:'https://i.pravatar.cc/500?img=12',tags:['Business','Startups','Strategy'],bio:'Founder and strategist helping emerging entrepreneurs validate ideas.',offers:[['Business Clarity Session',45,100]]},
{name:'Taylor Morgan',title:'Marketing Mentor',category:'Technology',price:65,img:'https://i.pravatar.cc/500?img=32',tags:['Marketing','Branding','Social Media'],bio:'Marketing leader focused on practical positioning and audience growth.',offers:[['Marketing Strategy',45,65]]}
];
let selectedMentor=mentors[0],selectedOffer=selectedMentor.offers[0];
function mentorCard(m){return `<article class="mentor-card" data-directory-link><img src="${m.img}" alt="${m.name}"><h3>${m.name}</h3><p>${m.title}</p><div class="price">Featured mentor preview</div><button class="btn light full">Browse live mentors</button></article>`}
function renderFeatured(){const el=document.getElementById('featuredMentors');if(el)el.innerHTML=mentors.slice(0,3).map(mentorCard).join('')}
function prepareBookingStep(){const booking=document.getElementById('booking');if(!booking)return;const panels=booking.querySelectorAll('.booking-grid > .panel');if(panels[1]){panels[1].querySelector('h3').textContent='Next: Choose an Available Time';const month=panels[1].querySelector('b'),calendar=panels[1].querySelector('.calendar'),times=panels[1].querySelector('.times');if(month)month.style.display='none';if(calendar)calendar.style.display='none';if(times)times.style.display='none';let note=panels[1].querySelector('.availability-note');if(!note){note=document.createElement('p');note.className='availability-note';note.style.cssText='color:var(--muted);line-height:1.6';note.textContent='After you choose a session, you’ll see only the mentor’s actual available dates and times.';panels[1].insertBefore(note,document.getElementById('continueBooking'))}const btn=document.getElementById('continueBooking');if(btn)btn.textContent='View Available Times'}}
function show(id){if(id==='directory'){location.href='mentor-directory.html';return}if(id==='mentorProfile'){location.href='mentor-directory.html';return}if(id==='login'){location.href='login.html';return}if(id==='role'){location.href='login.html?mode=create';return}if(id==='apply'){location.href='login.html?mode=create&role=mentor&return='+encodeURIComponent(location.origin+'/mentor-application.html');return}if(id==='dashboard'){location.href='dashboards.html';return}if(id==='logout'){return}document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));const el=document.getElementById(id);if(el){el.classList.add('active');window.scrollTo({top:0,behavior:'instant'})}document.querySelectorAll('#bottomNav button[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===id));document.getElementById('mobileMenu')?.classList.remove('open');if(id==='booking')prepareBookingStep()}
function renderBookingServices(){const el=document.getElementById('bookingServices');if(el)el.innerHTML=selectedMentor.offers.map((o,i)=>`<div class="service-option ${selectedOffer===o?'selected':''}" data-offer-index="${i}"><b>${o[0]}</b><small style="display:block;color:var(--muted);margin-top:4px">${o[1]} minutes · $${o[2]}</small></div>`).join('')}
renderFeatured();document.querySelector('.preview-strip')?.remove();
const legacyApply=document.querySelector('#apply .btn.primary');if(legacyApply){legacyApply.textContent='Create Account to Apply';legacyApply.onclick=()=>location.href='login.html?mode=create&role=mentor&return='+encodeURIComponent(location.origin+'/mentor-application.html')}
document.addEventListener('click',e=>{const how=e.target.closest('a[href="#how"]');if(how){e.preventDefault();location.href='how-it-works.html';return}const r=e.target.closest('[data-route]');if(r){e.preventDefault();show(r.dataset.route);if(r.dataset.route==='booking'){renderBookingServices();prepareBookingStep()}return}const c=e.target.closest('[data-directory-link],.mentor-card');if(c){e.preventDefault();location.href='mentor-directory.html';return}const offer=e.target.closest('[data-offer-index]');if(offer){selectedOffer=selectedMentor.offers[Number(offer.dataset.offerIndex)];renderBookingServices()}});
if(document.getElementById('menuBtn'))document.getElementById('menuBtn').onclick=()=>document.getElementById('mobileMenu').classList.add('open');if(document.getElementById('closeMenu'))document.getElementById('closeMenu').onclick=()=>document.getElementById('mobileMenu').classList.remove('open');
document.querySelectorAll('[data-role]').forEach(b=>b.addEventListener('click',()=>{location.href='login.html?mode=create&role='+encodeURIComponent(b.dataset.role)+(b.dataset.role==='mentor'?'&return='+encodeURIComponent(location.origin+'/mentor-application.html'):'')}));
if(document.getElementById('continueBooking'))document.getElementById('continueBooking').onclick=()=>{const [name,minutes,price]=selectedOffer;location.href=`booking-preview.html?mentor=${encodeURIComponent(selectedMentor.name)}&session=${encodeURIComponent(name)}&price=${price}&duration=${minutes}`};prepareBookingStep();
(()=>{if(!document.querySelector('script[data-auth-session]')){const a=document.createElement('script');a.src='auth-session.js';a.dataset.authSession='1';document.head.appendChild(a)}if(document.querySelector('script[data-writing-assist]'))return;const s=document.createElement('script');s.src='writing-assist.js';s.dataset.writingAssist='1';document.head.appendChild(s)})();