const mentors=[
{name:'Alexis Jordan',title:'Career Coach',category:'Career',price:75,img:'https://i.pravatar.cc/500?img=47',tags:['Career','LinkedIn','Job Search'],bio:'I help professionals gain clarity, build confidence, and create career paths they love.',offers:[['1:1 Career Coaching',45,75]]},
{name:'Marcus Williams',title:'Business Strategist',category:'Business',price:100,img:'https://i.pravatar.cc/500?img=12',tags:['Business','Startups','Strategy'],bio:'Founder and strategist helping emerging entrepreneurs validate ideas.',offers:[['Business Clarity Session',45,100]]},
{name:'Taylor Morgan',title:'Marketing Mentor',category:'Technology',price:65,img:'https://i.pravatar.cc/500?img=32',tags:['Marketing','Branding','Social Media'],bio:'Marketing leader focused on practical positioning and audience growth.',offers:[['Marketing Strategy',45,65]]}
];
let selectedMentor=mentors[0],selectedOffer=selectedMentor.offers[0];
function mentorCard(m){return `<article class="mentor-card" data-directory-link><img src="${m.img}" alt="${m.name}"><h3>${m.name}</h3><p>${m.title}</p><div class="price">Featured mentor preview</div><button class="btn light full">Browse live mentors</button></article>`}
function renderFeatured(){const el=document.getElementById('featuredMentors');if(el)el.innerHTML=mentors.slice(0,3).map(mentorCard).join('')}
function prepareBookingStep(){const booking=document.getElementById('booking');if(!booking)return;const panels=booking.querySelectorAll('.booking-grid > .panel');if(panels[1]){panels[1].querySelector('h3').textContent='Next: Choose an Available Time';const month=panels[1].querySelector('b'),calendar=panels[1].querySelector('.calendar'),times=panels[1].querySelector('.times');if(month)month.style.display='none';if(calendar)calendar.style.display='none';if(times)times.style.display='none';let note=panels[1].querySelector('.availability-note');if(!note){note=document.createElement('p');note.className='availability-note';note.style.cssText='color:var(--muted);line-height:1.6';note.textContent='After you choose a session, you’ll see only the mentor’s actual available dates and times.';panels[1].insertBefore(note,document.getElementById('continueBooking'))}const btn=document.getElementById('continueBooking');if(btn)btn.textContent='View Available Times'}}
function show(id){if(id==='directory'){location.href='mentor-directory.html';return}if(id==='mentorProfile'){location.href='mentor-directory.html';return}if(id==='login'){location.href='login.html';return}if(id==='role'){location.href='login.html?mode=create';return}if(id==='dashboard'){location.href='dashboards.html';return}if(id==='logout'){return}document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));const el=document.getElementById(id);if(el){el.classList.add('active');window.scrollTo({top:0,behavior:'instant'})}document.querySelectorAll('#bottomNav button[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===id));document.getElementById('mobileMenu')?.classList.remove('open');if(id==='booking')prepareBookingStep()}
function renderBookingServices(){const el=document.getElementById('bookingServices');if(el)el.innerHTML=selectedMentor.offers.map((o,i)=>`<div class="service-option ${selectedOffer===o?'selected':''}" data-offer-index="${i}"><b>${o[0]}</b><small style="display:block;color:var(--muted);margin-top:4px">${o[1]} minutes · $${o[2]}</small></div>`).join('')}
function installMentorPreScreen(){const section=document.getElementById('apply');if(!section)return;const fields=[...section.querySelectorAll('input,textarea')];const submit=section.querySelector('.btn.primary');if(!submit)return;submit.textContent='Submit';submit.onclick=e=>{e.preventDefault();const values=fields.map(x=>x.value.trim());if(values.some(v=>!v)){alert('Please complete all preliminary screening fields before submitting.');return}const prelim={full_name:fields[0]?.value.trim()||'',email:fields[1]?.value.trim()||'',location:fields[2]?.value.trim()||'',professional_title:fields[3]?.value.trim()||'',primary_expertise:fields[4]?.value.trim()||'',motivation:fields[5]?.value.trim()||''};sessionStorage.setItem('meMentorPreScreen',JSON.stringify(prelim));showMentorAccountPrompt()}}
function showMentorAccountPrompt(){document.getElementById('mentorAccountPrompt')?.remove();const overlay=document.createElement('div');overlay.id='mentorAccountPrompt';overlay.style.cssText='position:fixed;inset:0;z-index:9999;background:rgba(11,19,40,.5);display:grid;place-items:center;padding:20px';overlay.innerHTML=`<div style="width:min(520px,100%);background:#fff;border-radius:22px;padding:28px;box-shadow:0 24px 70px rgba(0,0,0,.25);text-align:center"><div style="font-size:32px">✓</div><h2 style="margin:10px 0">Preliminary screening submitted</h2><p style="color:#6f7586;line-height:1.6;margin:0">To proceed as a mentor, you’ll need to finalize creating your MentEducation account. After your account is created, we’ll bring you back to finish the remaining mentor application steps.</p><div style="display:grid;gap:10px;margin-top:22px"><button id="mentorCreateAccount" class="btn primary full">Create Mentor Account</button><button id="mentorPromptClose" class="btn light full">Not yet</button></div></div>`;document.body.appendChild(overlay);document.getElementById('mentorCreateAccount').onclick=()=>{const p=JSON.parse(sessionStorage.getItem('meMentorPreScreen')||'{}');const qs=new URLSearchParams({mode:'create',role:'mentor',return:location.origin+'/mentor-application.html'});if(p.email)qs.set('email',p.email);if(p.full_name)qs.set('name',p.full_name);location.href='login.html?'+qs.toString()};document.getElementById('mentorPromptClose').onclick=()=>overlay.remove()}
renderFeatured();document.querySelector('.preview-strip')?.remove();installMentorPreScreen();
document.addEventListener('click',e=>{const how=e.target.closest('a[href="#how"]');if(how){e.preventDefault();location.href='how-it-works.html';return}const r=e.target.closest('[data-route]');if(r){e.preventDefault();show(r.dataset.route);if(r.dataset.route==='booking'){renderBookingServices();prepareBookingStep()}return}const c=e.target.closest('[data-directory-link],.mentor-card');if(c){e.preventDefault();location.href='mentor-directory.html';return}const offer=e.target.closest('[data-offer-index]');if(offer){selectedOffer=selectedMentor.offers[Number(offer.dataset.offerIndex)];renderBookingServices()}});
if(document.getElementById('menuBtn'))document.getElementById('menuBtn').onclick=()=>document.getElementById('mobileMenu').classList.add('open');if(document.getElementById('closeMenu'))document.getElementById('closeMenu').onclick=()=>document.getElementById('mobileMenu').classList.remove('open');
document.querySelectorAll('[data-role]').forEach(b=>b.addEventListener('click',()=>{location.href='login.html?mode=create&role='+encodeURIComponent(b.dataset.role)}));
if(document.getElementById('continueBooking'))document.getElementById('continueBooking').onclick=async()=>{const {data:{session}}=await (window.__meAuthSb||{auth:{getSession:async()=>({data:{session:null}})}}).auth.getSession();if(!session){location.href='login.html?mode=create&role=mentee';return}const [name,minutes,price]=selectedOffer;location.href=`booking-preview.html?mentor=${encodeURIComponent(selectedMentor.name)}&session=${encodeURIComponent(name)}&price=${price}&duration=${minutes}`};prepareBookingStep();
(()=>{if(!document.querySelector('script[data-auth-session]')){const a=document.createElement('script');a.src='auth-session.js';a.dataset.authSession='1';document.head.appendChild(a)}if(document.querySelector('script[data-writing-assist]'))return;const s=document.createElement('script');s.src='writing-assist.js';s.dataset.writingAssist='1';document.head.appendChild(s)})();