const mentors=[
{name:'Alexis Jordan',title:'Career Coach',category:'Career',price:75,img:'https://i.pravatar.cc/500?img=47',tags:['Career','LinkedIn','Job Search'],bio:'I help professionals gain clarity, build confidence, and create career paths they love. With 8+ years in HR and coaching, I’m here to help you reach your next level.',offers:[['1:1 Career Coaching',45,75],['Resume Review',30,55],['Interview Prep',45,65]]},
{name:'Marcus Williams',title:'Business Strategist',category:'Business',price:100,img:'https://i.pravatar.cc/500?img=12',tags:['Business','Startups','Strategy'],bio:'Founder and strategist helping emerging entrepreneurs validate ideas, sharpen offers, and build sustainable businesses.',offers:[['Business Clarity Session',45,100],['Startup Strategy Deep Dive',60,135],['Offer Review',30,70]]},
{name:'Taylor Morgan',title:'Marketing Mentor',category:'Technology',price:65,img:'https://i.pravatar.cc/500?img=32',tags:['Marketing','Branding','Social Media'],bio:'Marketing leader focused on practical positioning, audience growth, and content systems that convert.',offers:[['Marketing Strategy',45,65],['Brand Review',45,80],['Content Planning',30,55]]},
{name:'Jordan Williams',title:'Real Estate Mentor',category:'Real Estate',price:70,img:'https://i.pravatar.cc/500?img=11',tags:['Real Estate','Licensing','Investing'],bio:'I help mentees understand real-estate career paths, licensing fundamentals, and early investment strategy.',offers:[['Real Estate Career Roadmap',45,70],['Licensing Q&A',30,55],['Investor Basics',60,95]]},
{name:'Danielle Brooks',title:'Healthcare Career Mentor',category:'Healthcare',price:60,img:'https://i.pravatar.cc/500?img=25',tags:['Healthcare','Pharmacy','Career'],bio:'I support people exploring healthcare careers with practical guidance on pathways, workplace growth, and next steps.',offers:[['Healthcare Career Session',45,60],['Pharmacy Pathway Q&A',30,50],['Professional Growth Session',60,85]]}
];
let selectedMentor=mentors[0],selectedOffer=selectedMentor.offers[0];
function mentorCard(m){return `<article class="mentor-card" data-mentor="${m.name}"><img src="${m.img}" alt="${m.name}"><h3>${m.name} <span style="color:var(--purple)">✓</span></h3><p>${m.title}</p><div class="stars">★★★★★ <span style="color:#666;font-size:12px">4.9</span></div><div class="tags">${m.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="price">From $${m.price} / session</div><button class="btn light full">View Profile</button></article>`}
function renderFeatured(){const el=document.getElementById('featuredMentors');if(el)el.innerHTML=mentors.slice(0,3).map(mentorCard).join('')}
function filterMentors(){const q=(document.getElementById('mentorSearch')?.value||'').trim().toLowerCase(),cat=document.getElementById('mentorCategory')?.value||'All Categories',list=mentors.filter(m=>{const hay=[m.name,m.title,m.category,...m.tags].join(' ').toLowerCase();return(!q||hay.includes(q))&&(cat==='All Categories'||m.category===cat)}),grid=document.getElementById('directoryMentors');if(grid)grid.innerHTML=list.map(mentorCard).join('');const count=document.getElementById('mentorCount');if(count)count.textContent=`${list.length} mentor${list.length===1?'':'s'} shown`;document.getElementById('mentorEmpty')?.classList.toggle('hidden',list.length>0)}
function prepareBookingStep(){const booking=document.getElementById('booking');if(!booking)return;const panels=booking.querySelectorAll('.booking-grid > .panel');if(panels[1]){panels[1].querySelector('h3').textContent='Next: Choose an Available Time';const month=panels[1].querySelector('b'),calendar=panels[1].querySelector('.calendar'),times=panels[1].querySelector('.times');if(month)month.style.display='none';if(calendar)calendar.style.display='none';if(times)times.style.display='none';let note=panels[1].querySelector('.availability-note');if(!note){note=document.createElement('p');note.className='availability-note';note.style.cssText='color:var(--muted);line-height:1.6';note.textContent='After you choose a session, you’ll see only the mentor’s actual available dates and times.';panels[1].insertBefore(note,document.getElementById('continueBooking'))}const btn=document.getElementById('continueBooking');if(btn)btn.textContent='View Available Times'}}
function show(id){if(id==='login'){location.href='login.html';return}if(id==='role'){location.href='login.html?mode=create';return}if(id==='dashboard'){location.href='dashboards.html';return}if(id==='logout'){return}document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));const el=document.getElementById(id);if(el){el.classList.add('active');window.scrollTo({top:0,behavior:'instant'})}document.querySelectorAll('#bottomNav button[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===id));document.getElementById('mobileMenu')?.classList.remove('open');if(id==='directory')filterMentors();if(id==='booking')prepareBookingStep()}
function openProfile(name){const m=mentors.find(x=>name.startsWith(x.name))||mentors[0];selectedMentor=m;selectedOffer=m.offers[0];document.getElementById('profileName').textContent=m.name+' ✓';document.getElementById('profileTitle').textContent=m.title;document.getElementById('profileImage').src=m.img;document.getElementById('profileBio').textContent=m.bio;document.getElementById('profileTags').innerHTML=m.tags.map(t=>`<span class="tag">${t}</span>`).join('');document.getElementById('profileOffers').innerHTML=m.offers.map(o=>`<div class="offer"><span><b>${o[0]}</b><small style="display:block;color:var(--muted);margin-top:4px">${o[1]} minutes</small></span><span><b>$${o[2]}</b></span></div>`).join('');renderBookingServices();show('mentorProfile')}
function renderBookingServices(){const el=document.getElementById('bookingServices');if(el)el.innerHTML=selectedMentor.offers.map((o,i)=>`<div class="service-option ${selectedOffer===o?'selected':''}" data-offer-index="${i}"><b>${o[0]}</b><small style="display:block;color:var(--muted);margin-top:4px">${o[1]} minutes · $${o[2]}</small></div>`).join('')}
renderFeatured();filterMentors();document.querySelector('.preview-strip')?.remove();
document.addEventListener('click',e=>{const r=e.target.closest('[data-route]');if(r){e.preventDefault();show(r.dataset.route);if(r.dataset.route==='booking'){renderBookingServices();prepareBookingStep()}}const c=e.target.closest('.mentor-card');if(c){e.preventDefault();openProfile(c.dataset.mentor)}const offer=e.target.closest('[data-offer-index]');if(offer){selectedOffer=selectedMentor.offers[Number(offer.dataset.offerIndex)];renderBookingServices()}const f=e.target.closest('[data-category]');if(f){document.getElementById('mentorCategory').value=f.dataset.category;filterMentors()}});
if(document.getElementById('mentorSearchBtn'))document.getElementById('mentorSearchBtn').onclick=filterMentors;if(document.getElementById('mentorSearch'))document.getElementById('mentorSearch').addEventListener('input',filterMentors);if(document.getElementById('mentorCategory'))document.getElementById('mentorCategory').addEventListener('change',filterMentors);if(document.getElementById('menuBtn'))document.getElementById('menuBtn').onclick=()=>document.getElementById('mobileMenu').classList.add('open');if(document.getElementById('closeMenu'))document.getElementById('closeMenu').onclick=()=>document.getElementById('mobileMenu').classList.remove('open');
document.querySelectorAll('[data-role]').forEach(b=>b.addEventListener('click',()=>{location.href='login.html?mode=create&role='+encodeURIComponent(b.dataset.role)}));
if(document.getElementById('continueBooking'))document.getElementById('continueBooking').onclick=()=>{const [name,minutes,price]=selectedOffer;location.href=`booking-preview.html?mentor=${encodeURIComponent(selectedMentor.name)}&session=${encodeURIComponent(name)}&price=${price}&duration=${minutes}`};prepareBookingStep();
(()=>{if(!document.querySelector('script[data-auth-session]')){const a=document.createElement('script');a.src='auth-session.js';a.dataset.authSession='1';document.head.appendChild(a)}if(document.querySelector('script[data-writing-assist]'))return;const s=document.createElement('script');s.src='writing-assist.js';s.dataset.writingAssist='1';document.head.appendChild(s)})();