import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors, radii, spacing } from '../../src/theme';

const days = [
  ['SUN','25'],['MON','26'],['TUE','27'],['WED','28'],['THU','29'],['FRI','30'],['SAT','31']
];
const times = ['10:00 AM – 11:00 AM','12:00 PM – 1:00 PM','2:00 PM – 3:00 PM','4:00 PM – 5:00 PM'];

export default function SelectTime(){
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
    <View style={s.top}><TouchableOpacity onPress={()=>router.back()}><Ionicons name="arrow-back" size={25} color={colors.navy}/></TouchableOpacity><Text style={s.title}>Select Date & Time</Text><Text style={s.tz}>EST⌄</Text></View>
    <View style={s.mentor}><View style={s.avatar}><Ionicons name="person" size={25} color="#8E7BBE"/></View><View style={{flex:1}}><Text style={s.name}>Jasmine Williams</Text><Text style={s.role}>Career Development</Text></View><View><Text style={s.price}>$85</Text><Text style={s.per}>session</Text></View></View>
    <View style={s.steps}>{['1','2','3','4'].map((n,i)=><View key={n} style={s.stepWrap}><View style={[s.step,i===0&&s.stepOn]}><Text style={[s.stepText,i===0&&s.stepTextOn]}>{n}</Text></View><Text style={s.stepLabel}>{['Date & Time','Your Info','Payment','Confirm'][i]}</Text></View>)}</View>
    <View style={s.calendar}><View style={s.monthRow}><Ionicons name="chevron-back" size={20} color={colors.navy}/><Text style={s.month}>May 2025</Text><Ionicons name="chevron-forward" size={20} color={colors.navy}/></View><View style={s.days}>{days.map(([d,n])=><TouchableOpacity key={d} style={s.day}><Text style={s.dayName}>{d}</Text><View style={[s.dayNum,n==='27'&&s.dayNumOn]}><Text style={[s.dayText,n==='27'&&s.dayTextOn]}>{n}</Text></View></TouchableOpacity>)}</View></View>
    <Text style={s.heading}>Available Times</Text>
    <View style={{gap:10}}>{times.map((t,i)=><TouchableOpacity key={t} style={[s.time,i===0&&s.timeOn]}><Text style={[s.timeText,i===0&&s.timeTextOn]}>{t}</Text><View style={[s.video,i===0&&{backgroundColor:'#8B5CF6'}]}><Ionicons name="videocam" size={16} color={i===0?'white':colors.purple}/><Text style={[s.videoText,i===0&&{color:'white'}]}>Video Call</Text></View></TouchableOpacity>)}</View>
    <TouchableOpacity style={s.continue} onPress={()=>router.push('/booking/confirmation')}><Text style={s.continueText}>Continue</Text></TouchableOpacity>
  </ScrollView></SafeAreaView>
}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.white},content:{padding:spacing.lg,paddingBottom:40},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},title:{fontSize:20,fontWeight:'800',color:colors.navy},tz:{fontSize:13,fontWeight:'700',color:colors.purple},mentor:{marginTop:24,borderWidth:1,borderColor:colors.line,borderRadius:radii.md,padding:14,flexDirection:'row',alignItems:'center',gap:12},avatar:{width:48,height:48,borderRadius:24,backgroundColor:colors.lavenderStrong,alignItems:'center',justifyContent:'center'},name:{fontSize:16,fontWeight:'800',color:colors.ink},role:{fontSize:12,color:colors.muted,marginTop:4},price:{fontSize:20,fontWeight:'800',color:colors.ink,textAlign:'right'},per:{fontSize:11,color:colors.muted,textAlign:'right'},steps:{flexDirection:'row',justifyContent:'space-between',marginTop:26},stepWrap:{alignItems:'center',width:'24%'},step:{width:32,height:32,borderRadius:16,backgroundColor:'#EEF0F5',alignItems:'center',justifyContent:'center'},stepOn:{backgroundColor:colors.purple},stepText:{fontSize:13,fontWeight:'800',color:colors.muted},stepTextOn:{color:'white'},stepLabel:{fontSize:10,color:colors.muted,marginTop:7,textAlign:'center'},calendar:{marginTop:24,borderWidth:1,borderColor:colors.line,borderRadius:radii.md,padding:16},monthRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},month:{fontSize:17,fontWeight:'800',color:colors.navy},days:{flexDirection:'row',justifyContent:'space-between',marginTop:18},day:{alignItems:'center'},dayName:{fontSize:10,color:colors.muted,fontWeight:'700'},dayNum:{width:36,height:36,borderRadius:18,alignItems:'center',justifyContent:'center',marginTop:8},dayNumOn:{backgroundColor:colors.purple},dayText:{fontSize:14,fontWeight:'700',color:colors.ink},dayTextOn:{color:'white'},heading:{fontSize:19,fontWeight:'800',color:colors.navy,marginTop:26,marginBottom:12},time:{height:58,borderWidth:1,borderColor:colors.line,borderRadius:14,paddingHorizontal:15,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},timeOn:{backgroundColor:colors.purple,borderColor:colors.purple},timeText:{fontSize:14,fontWeight:'700',color:colors.ink},timeTextOn:{color:'white'},video:{flexDirection:'row',alignItems:'center',gap:5,backgroundColor:colors.lavender,paddingHorizontal:10,paddingVertical:7,borderRadius:radii.pill},videoText:{fontSize:11,fontWeight:'700',color:colors.purple},continue:{marginTop:24,height:54,borderRadius:14,backgroundColor:colors.purple,alignItems:'center',justifyContent:'center'},continueText:{color:'white',fontSize:16,fontWeight:'800'}})
