import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors, radii, spacing } from '../../src/theme';

export default function MentorProfile(){
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
    <View style={s.top}><TouchableOpacity onPress={()=>router.back()}><Ionicons name="arrow-back" size={25} color={colors.navy}/></TouchableOpacity><View style={s.topActions}><Ionicons name="share-outline" size={24} color={colors.navy}/><Ionicons name="heart-outline" size={25} color={colors.navy}/></View></View>
    <View style={s.hero}><View style={s.avatar}><Ionicons name="person" size={56} color="#8E7BBE"/></View><View style={{flex:1}}><View style={s.nameRow}><Text style={s.name}>Jasmine Williams</Text><Ionicons name="checkmark-circle" size={18} color={colors.purple}/></View><Text style={s.role}>Career Development Mentor</Text><Text style={s.rating}>★ 4.9 <Text style={s.muted}>(128 reviews)</Text></Text><Text style={s.meta}>243 sessions</Text><Text style={s.meta}>Joined MentEducation in 2023</Text><Text style={s.available}>Available today</Text></View></View>
    <View style={s.tags}>{['Career Development','Leadership','Resume Help','Interview Prep','Job Search Strategy'].map(t=><Text key={t} style={s.tag}>{t}</Text>)}</View>
    <Text style={s.heading}>About Jasmine</Text><Text style={s.body}>I help professionals gain clarity, build confidence, and create strategic action plans to grow their careers and reach their goals.</Text><Text style={s.link}>Read more</Text>
    <View style={s.stats}>{[['4.9','Rating'],['243','Sessions'],['100%','Response Rate'],['2 yrs','Mentor']].map(([a,b])=><View key={b} style={s.stat}><Text style={s.statNum}>{a}</Text><Text style={s.statLabel}>{b}</Text></View>)}</View>
    <View style={s.sectionHead}><Text style={s.heading}>What Mentees Say</Text><Text style={s.link}>See all</Text></View>
    <View style={s.review}><Text style={s.reviewName}>Aaliyah B.</Text><Text style={s.muted}>2 weeks ago</Text><Text style={s.stars}>★★★★★</Text><Text style={s.body}>Jasmine helped me land my dream job! Her guidance was clear, practical, and exactly what I needed.</Text></View>
  </ScrollView><View style={s.bottom}><View><Text style={s.price}>$85<Text style={s.per}> / session</Text></Text></View><TouchableOpacity style={s.book} onPress={()=>router.push('/booking/select-time')}><Text style={s.bookText}>Book a Session</Text></TouchableOpacity></View></SafeAreaView>
}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.white},content:{padding:spacing.lg,paddingBottom:110},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},topActions:{flexDirection:'row',gap:18},hero:{flexDirection:'row',gap:16,marginTop:26},avatar:{width:120,height:145,borderRadius:18,backgroundColor:colors.lavenderStrong,alignItems:'center',justifyContent:'center'},nameRow:{flexDirection:'row',alignItems:'center',gap:5},name:{fontSize:21,fontWeight:'800',color:colors.navy},role:{fontSize:14,color:colors.muted,marginTop:5},rating:{fontSize:15,fontWeight:'700',color:colors.purple,marginTop:10},muted:{color:colors.muted,fontWeight:'500'},meta:{fontSize:13,color:colors.ink,marginTop:7},available:{alignSelf:'flex-start',fontSize:12,fontWeight:'800',color:colors.green,backgroundColor:colors.greenSoft,paddingHorizontal:9,paddingVertical:5,borderRadius:radii.pill,marginTop:9},tags:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:24},tag:{fontSize:12,fontWeight:'700',color:colors.purpleDark,backgroundColor:colors.lavender,paddingHorizontal:11,paddingVertical:8,borderRadius:radii.pill},heading:{fontSize:19,fontWeight:'800',color:colors.navy,marginTop:24},body:{fontSize:15,lineHeight:22,color:colors.ink,marginTop:9},link:{fontSize:14,fontWeight:'800',color:colors.purple,marginTop:8},stats:{flexDirection:'row',marginTop:22,borderWidth:1,borderColor:colors.line,borderRadius:radii.md,paddingVertical:16},stat:{flex:1,alignItems:'center'},statNum:{fontSize:19,fontWeight:'800',color:colors.navy},statLabel:{fontSize:10,color:colors.muted,marginTop:4,textAlign:'center'},sectionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},review:{borderWidth:1,borderColor:colors.line,borderRadius:radii.md,padding:16,marginTop:12},reviewName:{fontWeight:'800',color:colors.ink},stars:{color:colors.amber,letterSpacing:2,marginTop:10},bottom:{position:'absolute',left:0,right:0,bottom:0,backgroundColor:'white',borderTopWidth:1,borderTopColor:colors.line,paddingHorizontal:spacing.lg,paddingVertical:14,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},price:{fontSize:21,fontWeight:'800',color:colors.ink},per:{fontSize:12,fontWeight:'500',color:colors.muted},book:{backgroundColor:colors.purple,borderRadius:14,paddingHorizontal:28,paddingVertical:15},bookText:{color:'white',fontWeight:'800'}})
